# Generated by Django 3.1.6 on 2022-06-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(max_length=30, null=True, upload_to=''),
        ),
    ]
